life:
	gcc -ansi -pedantic -Wall life.c -o life
permute:
	gcc -ansi -pedantic -Wall permute.c -o permute
weird:
	gcc -ansi -pedantic -Wall weird.c -o weird
pi:
	gcc -ansi -pedantic -Wall pi.c -o pi
clean:
	rm life permute pi weird
